name: jakka_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  flutter:
    sdk: flutter
  firebase_ui_auth: ^1.13.1
  intl: ^0.18.1
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  path: ^1.9.0
  firebase_storage: ^11.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bicycle_icon.png
    - assets/clock.jpg
    - assets/JakkaCenter.png
    - assets/Mahidol_U.png
    - assets/profile.jpg
    - assets/qrcode.jpg
    - assets/news/
