// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMl0GyHL3vhovqnCe2Dk8D42LMEqHEuvk',
    appId: '1:118093147769:web:6dbaddcd7afbc816fdeea8',
    messagingSenderId: '118093147769',
    projectId: 'jakkaapp',
    authDomain: 'jakkaapp.firebaseapp.com',
    storageBucket: 'jakkaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJizBmGaqyb23HqajrSCCG94RmQLrulI',
    appId: '1:118093147769:android:b19075afcda0be5afdeea8',
    messagingSenderId: '118093147769',
    projectId: 'jakkaapp',
    storageBucket: 'jakkaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20oO2LhNN0J-bLCeci56bKL6NVSVPGGg',
    appId: '1:118093147769:ios:2d28671c5fa4f794fdeea8',
    messagingSenderId: '118093147769',
    projectId: 'jakkaapp',
    storageBucket: 'jakkaapp.appspot.com',
    iosBundleId: 'com.example.jakkaApp',
  );
}
